sudo: required
before_install:
- scripts/ci/before_install
script:
- scripts/ci/build
notifications:
  slack:
    secure: Gmxa3kkjfKQd7iFpkOJ7cE1bZsczHMExAC/uHkVYNUrn6KaPMzpEyi1ONfz8aCU+ML1Eyt2508wxFJ1kl/x9v4HqjINuAHTbboXYsX/HJuR8WHsA5/4eAaavp5yRTsqHuIjqGbuiuGCU3cPsQmq//o4Wzh6j1evIWGrkQcKXxuDvdX7rEDSR8zHsXpJ+SMyKYt+aCvR3/HRMM6d6upY3wko8Fs+DEz/sRnRKRFXTqS5DIrJFpQ5pzrpAgCp2YxrkWzHDCa6fCjhReSHDpjyDBW/OCXyzDEaUs6CDbNoZTa03Kk5kZhQQa5rXBQOG+yYKHDY5mWp/nSKaNtQiwiXfVjBeRsGHdPSDOL/5GFpvjjaHtnT5cxvVEOc0cCSw9K/XPc+vMQMjdbC0a+FF2GUT38W/a00ABgDXw7Zxz768btEZL1b8ta7p30iwgzYheOpiQFIROQg9ex95bR6GTmMTxdoG9hi0xc1oJ/VIXY4kpxz57UMGmyjWrNGDRSbgJRUhBKLsk84afx/GnZ88dnj/AnYhcsynwGULzXm+WoWQ2W1fkBddV2k0hphyAqpp+iVs8eBwflsWXOVhfWqY+RI8Lv/TOk+XClCwApjeddS+9+QaXbUWeAakkjGrF85ZmY3kWX0GeqJKUuOWMoa2TPO/X3CALcUv5D2lkj84MHI2ib0=
